apiVersion: v1
kind: Secret
metadata:
  name: k8s-monitor-secrets
  namespace: k8s-monitor
type: Opaque
stringData:
  POSTGRES_DB: k8smonitor
  POSTGRES_USER: k8smonitor
  POSTGRES_PASSWORD: M@rcus2031
  DATABASE_URL: postgresql://k8smonitor:M%40rcus2031@postgres-k8s-monitor:5432/k8smonitor
  gemini-api-key: AIzaSyBg5TC3njTJnERHtH5SjyRrhNuUR9eyP0k
  discord-webhook-url: https://discord.com/api/webhooks/1506653990866128907/X3JLqzm_VC7IPOMyNd9GLjH2gH-ZJ9yiXxZhCB0T6JDw4KSiNWD9x6S-wqZ1RC79klsh
  google-client-id: 116113012533-uq9g9n63m4h0r9e2l49ckjo674ss5n1l.apps.googleusercontent.com