kubectl create secret generic k8s-monitor-secrets \
  --namespace k8s-monitor \
  --from-literal=gemini-api-key=AIzaSyBg5TC3njTJnERHtH5SjyRrhNuUR9eyP0k \
  --from-literal=discord-webhook-url=https://discord.com/api/webhooks/1506653990866128907/X3JLqzm_VC7IPOMyNd9GLjH2gH-ZJ9yiXxZhCB0T6JDw4KSiNWD9x6S-wqZ1RC79klsh